import type { Metadata } from "next";
import {
  Cormorant_Garamond,
  Karla,
  Marcellus,
  Bodoni_Moda,
  Lora,
  Great_Vibes,
  Caveat,
  Lato,
} from "next/font/google";

import localFont from "next/font/local";

import "./globals.css";

const myFont1 = Cormorant_Garamond({
  variable: "--font-cormorantgaramond",
  subsets: ["latin"],
});

const myFont2 = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

const myFont3 = Marcellus({
  variable: "--font-marcellus",
  subsets: ["latin"],
  weight: "400",
});

const myFont4 = Bodoni_Moda({
  variable: "--font-bodonimoda",
  subsets: ["latin"],
});

const myFont5 = localFont({
  src: "../public/fonts/BelgianoSerif.woff2",
  display: "swap",
  variable: "--font-belgiano",
});

const myFont6 = localFont({
  src: "../public/fonts/Thesignature.woff2",
  display: "swap",
  variable: "--font-signature",
});

const myFont7 = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const myFont8 = Great_Vibes({
  variable: "--font-greatvibes",
  subsets: ["latin"],
  weight: "400",
});

const myFont9 = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${myFont1.variable} 
          ${myFont2.variable} 
          ${myFont3.variable} 
          ${myFont4.variable} 
          ${myFont5.variable} 
          ${myFont6.variable} 
          ${myFont7.variable} 
          ${myFont8.variable} 
          ${myFont9.variable} 
          antialiased`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
